# This workflow runs the dummy ci tests on the application source code and if they succeed it runs terraform deployment job that
# installs the latest version of Terraform CLI and configures the Terraform CLI with aws provider and s3 backend
# On pull request events, this workflow will run `terraform init`, `terraform fmt`, `terraform validate`, and `terraform plan`
# and shows the terraform plan in the pull request using github actions bot. On push events
# to the "main" branch, `terraform apply` will be executed.
#

name: Deploy Core Infrastructure via Terraform

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "CI passed"
  terraform:
    name: 'Terraform'
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.2

    - name: Terraform Init
      run: cd infra && terraform init

    - name: Terraform Lint
      run: cd infra && terraform fmt -check

    - name: Terraform validate
      run:  cd infra && terraform validate

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: cd infra && terraform plan -out=plan.out
    - run: cd infra && terraform show -no-color plan.out > plan.txt
    - run: cd infra && terraform show -json plan.out > plan.json
    - uses: ahmadnassri/action-terraform-report@v3
      if: github.event_name == 'pull_request'
      with:
        # tell the action the plan outputs
        terraform-text: infra/plan.txt
        terraform-json: infra/plan.json
        remove-stale-reports: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
      run: cd infra && terraform apply -auto-approve plan.out
